version: '3'
services:
    py3s:
        build: .
        container_name: 'go11c'
        working_dir: '/go/src/github.com/skxeve/TryChi'
        tty: true
        volumes:
            - .:/go/src/github.com/skxeve/TryChi
        environment:
            - "TZ=Asia/Tokyo"
        ports:
            - "8080:8080"
